config-version: 2
name: 'pendo'
version: '0.5.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  pendo:
    intermediate:
      +materialized: view
      +schema: int_pendo
    +materialized: table
    +schema: pendo
vars:
  pendo:
    account_history: "{{ ref('stg_pendo__account_history') }}"
    application_history: "{{ ref('stg_pendo__application_history') }}"
    event: "{{ ref('stg_pendo__event') }}"
    feature_event: "{{ ref('stg_pendo__feature_event') }}"
    feature_history: "{{ ref('stg_pendo__feature_history') }}"
    group: "{{ ref('stg_pendo__group') }}"
    guide_event: "{{ ref('stg_pendo__guide_event') }}"
    guide_history: "{{ ref('stg_pendo__guide_history') }}"
    guide_step_history: "{{ ref('stg_pendo__guide_step_history') }}"
    page_event: "{{ ref('stg_pendo__page_event') }}"
    page_history: "{{ ref('stg_pendo__page_history') }}"
    page_rule_history: "{{ ref('stg_pendo__page_rule_history') }}"
    user: "{{ ref('stg_pendo__user') }}"
    visitor_history: "{{ ref('stg_pendo__visitor_history') }}"
    poll: "{{ ref('stg_pendo__poll') }}"
    poll_event: "{{ ref('stg_pendo__poll_event') }}"
    visitor_account_history: "{{ ref('stg_pendo__visitor_account_history') }}"
    pendo__event_pass_through_columns: []
    pendo__feature_event_pass_through_columns: []
    pendo__page_event_pass_through_columns: []
    pendo__account_history_pass_through_columns: []
    pendo__visitor_history_pass_through_columns: []
