config-version: 2

name: 'pendo_integration_tests'
version: '1.1.0'

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "pendo_{{ var('directed_schema','dev') }}"

vars:
  consistency_test_exclude:
    ## String agg'd 
    - rules
    - page_rules
    ## The previous logic can be unpredictable due to identical timestamps
    - previous_feature_name
    - previous_feature_page_id
    - previous_feature_page_name
    - previous_feature_product_area_name
    - previous_feature_product_area_id
    - previous_feature_id
    - previous_feature_event_at
    - previous_feature_num_minutes
    - previous_feature_num_events
    - previous_page_id
    - previous_page_name
    - previous_product_area_name
    - previous_page_product_area_id
    - previous_page_event_at
    - previous_page_num_events
    - previous_page_num_minutes

  pendo:
    pendo_schema: pendo_integration_tests
    pendo_account_history_identifier: "account_history"
    pendo_application_history_identifier: "application_history"
    pendo_event_identifier: "event"
    pendo_feature_event_identifier: "feature_event"
    pendo_feature_history_identifier: "feature_history"
    pendo_group_identifier: "group_data"
    pendo_guide_event_identifier: "guide_event"
    pendo_guide_history_identifier: "guide_history"
    pendo_guide_step_history_identifier: "guide_step_history"
    pendo_page_event_identifier: "page_event"
    pendo_page_history_identifier: "page_history"
    pendo_page_rule_history_identifier: "page_rule_history"
    pendo_user_identifier: "user"
    pendo_visitor_history_identifier: "visitor_history"
    pendo_poll_identifier: "poll"
    pendo_poll_event_identifier: "poll_event"
    pendo_visitor_account_history_identifier: "visitor_account_history"
    
    pendo__event_pass_through_columns: []
    pendo__feature_event_pass_through_columns: []
    pendo__page_event_pass_through_columns: []
    pendo__account_history_pass_through_columns: []
    pendo__visitor_history_pass_through_columns: []
    
seeds:
  +docs:
    show: False
  pendo_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
    guide_event:
      +column_types:
        latitude: numeric
        longitude: numeric
        timestamp: timestamp
    application_history:
      +column_types:
        subscription_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        last_updated_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    guide_history:
      +column_types:
        created_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        last_updated_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
    account_history:
      +column_types:
        id_hash: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    feature_history:
      +column_types:
        last_updated_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        group_id: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        created_at: timestamp
    feature_event:
      +column_types:
        timestamp: timestamp
    group_data:
      +column_types:
        last_updated_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        color: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        id: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
    user:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    page_history:
      +column_types:
        created_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        last_updated_by_user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        group_id: "{{ 'string' if target.name in ['bigquery','spark','databricks'] else 'varchar' }}"
        created_at: timestamp
    page_event:
      +column_types:
        timestamp: timestamp
    visitor_history:
      +column_types:
        id_hash: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"

flags:
  send_anonymous_usage_stats: False


  use_colors: True
